import { createAsyncAction } from 'redux-helper'
import { createAction } from 'redux-actions'

export const updateLoanAccountId = createAction('loan/UPDATE_LOAN_ACCOUNT_ID')
export const updateCollateralAssetId = createAction('loan/UPDATE_COLLATERAL_ASSET_ID')
export const updateLoanAssetId = createAction('loan/UPDATE_ASSET_ID')
export const updateLiquidationThresholdLimit = createAction('loan/UPDATE_LIQUIDATION_THRESHOLD_LIMIT')
export const updateNextLoanPackageId = createAction('loan/UPDATE_NEXT_PACKAGE_ID')
export const updateActiveLoanPackage = createAction('loan/UPDATE_ACTIVE_PACKAGE')
export const updateLoanPackageInfo = createAction('loan/UPDATE_PACKAGE_INFO')
export const updateNextLoanId = createAction('loan/UPDATE_NEXT_LOAN_ID')
export const updateCurrentBTCPrice = createAction('loan/UPDATE_BTC_PRICE')
export const updateTotalLoan = createAction('loan/UPDATE_TOTAL')
export const updateLoans = createAction('loan/UPDATE_LOANS')
export const setActiveLoanPackage = createAction('loan/SET_LOANS_PACKAGE')
export const updateGlobalWarningThreshold = createAction('loan/UPDATE_GLOBAL_WARNING_THRESHOLD')
export const updateGlobalLiquidationThreshold = createAction('loan/UPDATE_GLOBAL_LIQUIDATION_THRESHOLD')
export const updateLiquidationLoans = createAction('loan/UPDATE_LIQUIDATION_LOANS')

export const receiveLoanIds = createAction('loan/RECEIVE_LOAN_IDS')
export const subscribeLoans = createAction('loan/SUBSCRIBE_LOANS')
export const unsubscribeLoans = createAction('loan/UNSUBSCRIBE_LOANS')
export const subscribeBTCPrice = createAction('loan/SUBSCRIBE_BTC_PRICE')
export const unsubscribeBTCPrice = createAction('loan/UNSUBSCRIBE_BTC_PRICE')

export const getLoanAccountId = createAsyncAction('loan/LOAN_ACCOUNT_ID')
export const getCollateralAssetId = createAsyncAction('loan/GET_COLLATERAL_ASSET_ID')
export const getLoanAssetId = createAsyncAction('loan/GET_ASSET_ID')
export const getLiquidationThresholdLimit = createAsyncAction('loan/GET_LIQUIDATION_THRESHOLD_LIMIT')
export const getNextLoanPackageId = createAsyncAction('loan/GET_NEXT_PACKAGE_ID')
export const getActiveLoanPackage = createAsyncAction('loan/GET_ACTIVE_PACKAGE')
export const getLoanPackageInfo = createAsyncAction('loan/GET_PACKAGE_INFO')
export const getNextLoanId = createAsyncAction('loan/GET_NEXT_LOAN_ID')
export const getLoanByAccount = createAsyncAction('loan/GET_BY_ACCOUNT')
export const getCurrentBTCPrice = createAsyncAction('loan/GET_BTC_PRICE')
export const getTotalLoan = createAsyncAction('loan/GET_TOTAL')
export const getLoans = createAsyncAction('loan/GET_LOANS')
export const getGlobalWarningThreshold = createAsyncAction('loan/GET_GLOBAL_WARNING_THRESHOLD')
export const getGlobalLiquidationThreshold = createAsyncAction('loan/GET_GLOBAL_LIQUIDATION_THRESHOLD')
export const getLiquidatingLoans = createAsyncAction('loan/GET_LIQUIDATION_LOANS')

export const setCollateralAssetId = createAsyncAction('loan/SET_COLLATERAL_ASSET_ID')
export const setGlobalLtvLimit = createAsyncAction('loan/SET_GLOBAL_LTV_LIMIT')
export const setLoanAssetId = createAsyncAction('loan/SET_LOAN_ASSET_ID')
export const setGlobalLiquidationThreshold = createAsyncAction('loan/SET_GLOBAL_LIQUIDATION_THRESHOLD')
export const setGlobalWarningThreshold = createAsyncAction('loan/SET_GLOBAL_WARNING_THRESHOLD')
export const createLoanPackage = createAsyncAction('loan/CREATE_PACKAGE')
export const disableLoanPackage = createAsyncAction('loan/DISABLE_PACKAGE')
export const applyLoan = createAsyncAction('loan/APPLY')
export const repay = createAsyncAction('loan/REPAY')
export const addCollateral = createAsyncAction('loan/ADD_COLLATERAL')
export const borrow = createAsyncAction('loan/BORROW')
